<?php

require_once 'JWT.php';

/**
 * Implementation of hook_menu().
 */
function diff_io_menu() {

  $items['admin/settings/diff_io'] = array(
    'title' => 'diff.io ' . t('settings'),
    'description' => t('Configure') . ' diff.io',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('diff_io_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'diff_io.admin.inc'
  );

  return $items;
}

function diff_io_url($url1, $url2 = '') {

  # get the values for the account
  $apikey = variable_get('diff_io_api_key', '');
  $secret = variable_get('diff_io_secret_key', '');
  $host = variable_get('diff_io_host', 'https://api.diff.io');

  # do not generate requests that the server will just drop
  if( empty( $apikey ) || empty( $secret ) || empty( $host ) ) {
    drupal_watchdog( t('Cannot generate a valid diff.io request, required module settings are missing.') );
    return "";
  }

  # declare the url to capture and diff
  $claims = array(
    "iss" => $apikey,
    "url1" => $url1
  );

  # add url2 for page vs page
  if( !empty( $url2 ) ) {
    $claims["url2"] = $url2;
  }
  # create a jti for this request, at this point in microtime
  $claims["jti"] = sha1( serialize( $claims ) ) . microtime(true);

  # generate token
  $jwt = JWT::encode($claims, $secret, "HS256");

  return "{$host}{$apikey}/{$jwt}";
}

function diff_io_call( $url1, $url2='' ){

  $calls_this_month = (int) variable_get('diff_io_monthly_calls:'. date("Y-m"), '0');

  $monthly_max = (int) variable_get('diff_io_monthly_max', '100');

  if( $calls_this_month < $monthly_max ){

    $call = drupal_http_request( diff_io_url( $url1, $url2 ) );

    // only record this against the monthly limit if call completed
    if( $call->code == 200 ){
      variable_set('diff_io_monthly_calls:'. date("Y-m"), ($calls_this_month+1) );

      // initial response will be a redirect to a then 200 json page
      // $call->data == { "diff": "io", "status": "pending", "rate": "1/60", "queue": "1/2000" }

      // $call->code == 200
      //   then $call->redirect_url == https://diffio.global.ssl.fastly.net/v1/diffs/{date}/{jobid}/results.json

      // @todo: better handle the error case if call didn't work, failed, didn't have a redirect_url property, etc.
      return $call->redirect_url;

    }

    // call did not 200, so...
    watchdog('diff_io', "Diff.io call resulted in a non-200 response. data: %url1 %url2", array('%url1' => $url1, '%url2' => $url2), WATCHDOG_WARNING);

  }
  else{
    watchdog('diff_io', "Over allowed limit for this month: %so_far/%max", array('%so_far' => $calls_this_month, '%max' => $monthly_max), WATCHDOG_ERROR);
  }
  return false;
}
function diff_io_node_update($node){

  $url = url('node/' . $node->nid, array('absolute' => TRUE) );
  drupal_set_message($url);
  // http://drupal-7-37.dd:8083/node/6
  // http://drupal-7-37.dd:8083/somenewpage
}

// function diff_io_post_insert($nid) {
// $nodeurl = url('node/'. $node->nid);
// $alias = drupal_get_path_alias('node/37');
// }